#!/usr/bin/env python3
# Specification: artisanRandom.md, generated 2026-08-12 19:25:37 CEST
# Coding guidelines: coding_details.md, August 2026
# Generated by OpenAI GPT-5.6 Luna on 2026-08-12 19:25:37 CEST

import argparse
import hashlib
import secrets
import sys


DEFAULT_INPUT = "numbers.txt"
DEFAULT_WORDLIST = "bip39.txt"
NUMBER_COUNT = 23
WORD_COUNT = 24
MAX_NUMBER = 1999
WORDLIST_SIZE = 2048


def read_numbers(filename):
    """Read and validate the 23 four-digit input numbers."""
    try:
        file = open(filename, "r", encoding="utf-8")
        lines = file.read().splitlines()
        file.close()
    except OSError as error:
        raise ValueError("cannot read input file: {0}".format(error))

    if len(lines) != NUMBER_COUNT:
        raise ValueError(
            "input file must contain exactly {0} lines".format(NUMBER_COUNT)
        )

    numbers = []

    for line in lines:
        if len(line) != 4:
            raise ValueError(
                "each input value must contain exactly four digits"
            )

        for character in line:
            if character < "0" or character > "9":
                raise ValueError(
                    "input values must contain only decimal digits"
                )

        value = int(line)

        if value > MAX_NUMBER:
            raise ValueError(
                "input values must be between 0000 and 1999"
            )

        numbers.append(value)

    return numbers


def read_wordlist(filename):
    """Read and validate the 2048-word BIP39 wordlist."""
    try:
        file = open(filename, "r", encoding="utf-8")
        lines = file.read().splitlines()
        file.close()
    except OSError as error:
        raise ValueError("cannot read wordlist: {0}".format(error))

    if len(lines) != WORDLIST_SIZE:
        raise ValueError(
            "wordlist must contain exactly {0} lines".format(WORDLIST_SIZE)
        )

    words = []

    for expected_index in range(WORDLIST_SIZE):
        line = lines[expected_index].strip()
        fields = line.split()

        if len(fields) == 1:
            word = fields[0]
        elif len(fields) == 2:
            index_text = fields[0]
            word = fields[1]

            if len(index_text) != 4:
                raise ValueError(
                    "invalid wordlist index on line {0}".format(
                        expected_index + 1
                    )
                )

            if not index_text.isdigit():
                raise ValueError(
                    "invalid wordlist index on line {0}".format(
                        expected_index + 1
                    )
                )

            index = int(index_text)

            if index != expected_index:
                raise ValueError(
                    "wordlist index does not match line {0}".format(
                        expected_index + 1
                    )
                )
        else:
            raise ValueError(
                "invalid wordlist line {0}".format(expected_index + 1)
            )

        words.append(word)

    return words


def build_entropy(numbers, extra_bits):
    """Build the 256-bit entropy value."""
    entropy = 0

    for number in numbers:
        entropy = (entropy << 11) | number

    entropy = (entropy << 3) | extra_bits

    return entropy


def calculate_checksum(entropy):
    """Return the eight-bit BIP39 checksum."""
    entropy_bytes = entropy.to_bytes(32, byteorder="big")
    digest = hashlib.sha256(entropy_bytes).digest()

    return digest[0]


def generate_words(numbers, wordlist):
    """Convert the entropy into the 24 BIP39 words."""
    extra_bits = secrets.randbits(3)
    entropy = build_entropy(numbers, extra_bits)
    checksum = calculate_checksum(entropy)

    last_index = (extra_bits << 8) | checksum

    words = []

    for number in numbers:
        words.append(wordlist[number])

    words.append(wordlist[last_index])

    return words


def print_words(words):
    """Print the numbered BIP39 recovery phrase."""
    for index in range(WORD_COUNT):
        print("{0:02d} {1}".format(index + 1, words[index]))


def parse_arguments():
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Generate a 24-word BIP39 recovery phrase."
    )
    parser.add_argument(
        "-i",
        "--input",
        default=DEFAULT_INPUT,
        help="input file (default: {0})".format(DEFAULT_INPUT),
    )
    parser.add_argument(
        "-w",
        "--wordlist",
        default=DEFAULT_WORDLIST,
        help="BIP39 wordlist (default: {0})".format(DEFAULT_WORDLIST),
    )

    return parser.parse_args()


def main():
    """Run ArtisanRandom."""
    arguments = parse_arguments()

    try:
        numbers = read_numbers(arguments.input)
        wordlist = read_wordlist(arguments.wordlist)
        words = generate_words(numbers, wordlist)
    except ValueError as error:
        print("Error: {0}".format(error), file=sys.stderr)
        return 1

    print_words(words)

    return 0


if __name__ == "__main__":
    sys.exit(main())
